options:
  merge-default-rules: false
  max-warnings: 0

files:
  include: '**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**'

rules:
  # turn off
  no-css-comments: 0
  single-line-per-selector: 0
  no-color-keywords: 0
  nesting-depth: 0
  border-zero: 0
  no-qualifying-elements: 0
  force-attribute-nesting: 0
  force-pseudo-nesting: 0

  # warning
  no-warn: 1
  no-debug: 1

  # error
  extends-before-mixins: 2
  no-ids: 2
  hex-notation:
    - 2
    - style: uppercase
  quotes: 2
  clean-import-paths: 2
  variable-name-format: 2
  leading-zero: 2
  no-important: 2
  indentation:
    - 2
    - size: 2
  force-element-nesting: 2
  no-vendor-prefixes: 2
  pseudo-element: 2
  no-trailing-zero: 2
  class-name-format:
    - 2
    - convention: camelcase
  no-color-literals: 2
  no-duplicate-properties: 2
  zero-unit: 2
  shorthand-values: 2
  placeholder-in-extend: 2
  placeholder-name-format: 2
  hex-length: 2
  no-misspelled-properties:
    - 2
    - extra-properties:
        - -webkit-overflow-scrolling
        - -ms-flex-align
  no-transition-all: 2
  final-newline: 2
  mixins-before-declarations: 2
  extends-before-declarations: 2
  trailing-semicolon: 2
  space-after-colon: 2
  space-before-brace: 2
  attribute-quotes: 2
  no-empty-rulesets: 2
  declarations-before-nesting: 2
  no-mergeable-selectors: 2
  space-after-comma: 2
  empty-line-between-blocks:
    - 2
    - ignore_single_line_blocks: false
